# Generated by Django 4.2.2 on 2023-06-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0002_alter_phototech_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototech',
            name='title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
    ]
