# Generated by Django 4.2.2 on 2023-06-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0004_ratingstar_alter_technics_options_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
