# Generated by Django 4.2.2 on 2023-07-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0005_delete_rating_delete_ratingstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='price',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
