# Generated by Django 4.2.2 on 2023-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0006_technics_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
