# Generated by Django 4.2.2 on 2023-07-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0007_alter_technics_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='youtube',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
