# Generated by Django 4.2.2 on 2023-07-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0008_technics_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='youtube',
            field=models.CharField(help_text='https://www.youtube.com/watch?v=PcIUnpSwhFk', max_length=50),
        ),
    ]
